### PR TITLE
PP+: Hoon pretty printer improvements

### PR DESCRIPTION
**Pull request by sidnym-ladrut**

### CODE REVIEW

**Comment by sidnym-ladrut** [comment]
Tagging: @joemfb, @belisarius222, @jackfoxy, @marcusmiguel

**Comment by belisarius222** [comment]
I don't think we need to change the type of type to try this.  We can use the `%hint` type, created by the `$+` rune, to name types.  Then we can write a pretty printer that honors those hints by looking up a gate from a `(map mark $-(vase tank))` where the `mark` key is extracted from the `%hint` type.  Making a new printing core makes sense, but making a whole new type of type doesn't strike me as necessary.

**Comment by sidnym-ladrut** [comment]
> I don't think we need to change the type of type to try this. We can use the `%hint` type, created by the `$+` rune, to name types. 

This is probably a good idea. If we want to refactor the heuristic type checking in `+us` to use `%hint` pretty printing, this will require adding `$+` annotations to the heuristics types, including type-builders like `+list`, `+set`, and `+map`. I don't know how tricky this would be; if it's simple, I think it's definitely worth it.

> Then we can write a pretty printer that honors those hints by looking up a gate from a `(map mark $-(vase tank))` where the `mark` key is extracted from the `%hint` type.

On the topic of the structure of the pretty printer gate, I had originally envisioned using a `+map` as well, but I think it'll actually be simpler to use an en-vased core with `%mark`-named arms instead. I suspect that the recursive structures of `$type` and `$tank` are easier to process via recursive calls in a single core rather than across cores; in one core, each `%mark` arm can easily produce its own portion of the `$tank` tree and recurse to a base arm to handle the rest. This may also be possible with disparate cores, but I think it will require a more complicated core signature; each `%mark` handler will need to indicate to the base handler how much of the `$type` it consumed and where in the `%tank` structure the process should recurse/continue.

**Comment by belisarius222** [comment]
> this will require adding `$+` annotations to the heuristics types, including type-builders like `+list`, `+set`, and `+map`

Yes.  The handler functions for those hints need to receive the entire enclosed type, and they need to have access to the actual printing function itself, so that complex recursive types can be handled properly.  For example, to print a `(set (list (set @)))`, the type looks like
```hoon
:+  %hint  %set   :+  %hold  ::  ..., outer set
:+  %hint  %list  :+  %hold  ::  ...
:+  %hint  %set   :+  %hold  ::  ..., inner set
...
```

The basic printer needs to call the `%set` printer, which then needs to call *back into* the basic printer to print the type of the set element.  Similarly, when encountering the inner list, the basic printer needs to call the `%list` printer, which needs to call back into the basic printer again to print the type of the list element, and the set printer needs to run again for the inner set.

The call stack then looks like this, with the most recently called function on top:
```
%atom printer  ::  (element of inner set)
basic printer
%set printer  :: inner set (element of list)
basic printer
%list printer  ::  list (element of outer set)
basic printer
%set printer  ::  outer set
```

The `%atom` printer is probably an implementation detail of the basic printer, although we could alternatively have a map of aura printer functions along with the map of type-hint printer functions.

I think this call stack could be achieved by having each mark printer function take in the basic printer as an argument, like this:
```hoon
=|  printers=(map mark $-([=vase printer=$-(vase tank)] tank))
|%
++  basic-printer
  |=  =vase
  ^-  tank
  =/  =type  p.vase
  ?-    type
      [%hint *]
    =/  mark-printer  (~(get by printers) p.type)
    ?~  mark-printer  $(p.vase q.type)
    (u.mark-printer [q.type p.vase] ..$)  ::  pass reference to ourselves into the mark printer
  ::
      *  !!
  ==
::
++  print-set
  |=  [=vase printer=$-(vase tank)]
  ^-  tank
  =/  [=type =hoon]  ?>(?=(%hold -p.vase) p.vase)
  =/  element-type=type  (~(play ut type) hoon)
  =/  items=(list *)  (slum |=(s=(set *) ~(tap in s)) q.vase)
  :+  %rose  [[' ' ~] ['{' ~] ['}' ~]]
  ^-  (list tank)
  (turn items |=(n=* (printer element-type n)))
::
++  print-list
  |=  [=vase printer=$-(vase tank)]
  ^-  tank
  !!  ::  looks like +print-set but encloses elements in "~[]" or "(list ...)" instead of "{}"
--
```

**Pull request merged**
