### PR TITLE
update UIP-0100

### PR DESCRIPTION
**Pull request by matthew-levan**

### CODE REVIEW

**Comment by dr-frmr** [comment]
Proposed scry request cache spec:

1. When a fine request is heard, the runtime must place that request in an in-memory cache. This request will contain the `path`, the requesting `ship`, and an expiration `time` equal to time of request + 3 minutes*. If a request is heard that matches one already in the cache, that cache entry is replaced with a newly-calculated expiration time.

2. When a new `[%grew path]` effect is heard from arvo, the runtime must first place the data at that path in its scry cache, then find all cached requests matching that path and respond.

3. Every few minutes, the runtime should trigger an "expiry check" that removes all cached scry requests past their expiration time. Note that it's possible for an expired request to be responded to, if this expiry check occurs less frequently than every 3 minutes. This is acceptable, and the frequency of the expiry check can be tuned for performance.

In order to make all three operations fast, a data structure should be designed that has fast `put` and `get` with regards to `path`, but also fast removal by expiry `time`. This could be some kind of queue combined with a hashtable...


* 3 minutes determined by adding 1 minute to the subscriber-side fine protocol maximum backoff time of 2 minutes

**Comment by belisarius222** [comment]
I wonder if there's a good space/time complexity tradeoff here: have just one "last-requested" time for each path for which there is an open request.  Each time a new request comes in over the network for a path, its last-requested time gets reset to `now`.  The pending interest table data structure could be `(map path [last-requested=@da requesters=(set ship)])`.  This means when a new request packet comes in, we also `(~(put in requesters) ship)`, which no-ops if the ship was already there.

This design would consolidate the timer information into a smaller set of dates: instead of one date per requesting ship, which could be quite large, it only stores one date per path, and there will often be many ships waiting to hear on a single path.

A single global timer every few minutes could delete the entries for paths that nobody has asked for recently.  This uses extra space temporarily, since if many ships had requested a path but were offline for a long time, then that state must be maintained as long as a single ship is still asking.  The extra state does get cleared, though, whenever the request resolves, or if everyone stops asking.  There is also a network bandwidth cost of one extra packet per dead ship per request.  Iterating through the set of open requests on the timer should be relatively quick, though.

Perhaps there is a data structure that would be efficient for all the different access patterns that need to happen here.  I haven't thought of one yet though.

**Comment by dr-frmr** [comment]
@belisarius222 that structure makes sense to me; the cost of holding on to "dead requesters" as long as there's an outstanding request for the path seems worthwhile given how much it simplifies the problem.

**Comment by matthew-levan** [comment]
What if we switched to `(map path [last-requested=@da requesters=(qeu ship) expiry-marker=@p)` where the `expiry-marker` is a ship in the `requesters` queue that marks the place where all ships ahead of it have non-expired requests and all ships after it have the opposite? 

Imagine: a requester `~zod` sends a request to `~nec` for a path which does not yet have data on it, say `~nec/future/scry/path`. Once `~nec` receives the scry request, `~zod` gets "added" to the `requesters` queue *and* is set as the `expiry-marker` at the same time. Then, many more ships make requests for data at the same path. Three minutes pass by, there is still no data published at `~nec/future/scry/path`, and the "cleanup timer" fires. At that moment, the cleanup algorithm is executed, which "removes" any ships in the `requesters` queue which happen to be positioned *at or after* the `expiry-marker` ship, and then updates the `expiry-marker` to the first ship in the queue (whoever that may be). In the case of this example, the first cleanup won't remove any ships from the queue because there won't yet be any after `~zod`, the original `expiry-marker` ship. After the initial cleanup, all of our ships will be marked at risk for removal from the queue. Upon the next cleanup timer's firing, the cleanup process would remove all the ships in the `requesters` queue, assuming there's still no data published at the original scry path.

Does this make sense? The only issue I see with this approach is that you could have the ship duplicates added to the `requesters` queue...

**Comment by mopfel-winrux** [comment]
@belisarius222 It could also be a `(set expiry=@da requester=@p)`, but i think youre right its still extra work,

**Comment by matthew-levan** [comment]
Stale.

**Pull request closed without merging**
